// swift-tools-version: 5.10
// The swift-tools-version declares the minimum version of Swift required to build this package.

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
#if canImport(AppleProductTypes) // swift package dump-package fails because of this
import AppleProductTypes

let package = Package(
    name: "TestLibrary",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "TestLibrary Library", // has to be named different from the iOSApplication or Swift Playgrounds won't open correctly
            targets: ["TestLibrary"]
        ),
        .iOSApplication(
            name: "TestLibrary", // needs to match package name to open properly in Swift Playgrounds
            targets: ["TestAppModule"],
            teamIdentifier: "3QPV894C33",
            displayVersion: "1.5.1",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .developerTools
        )
    ],
    dependencies: [
        .package(url: "https://github.com/kudit/Device", "2.1.4"..<"3.0.0")
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(
            name: "TestLibrary",
            dependencies: [
                .product(name: "Device Library", package: "device")
            ],
            path: "Sources"
            // If resources need to be included, include here
//            resources: [.process("Resources")]
        ),
        .executableTarget(
            name: "TestAppModule",
            dependencies: [
                "TestLibrary"
            ],
            path: "Development"
        )
    ]
)
#else // for Swift Package compiling for https://swiftpackageindex.com/add-a-package (not used when importing in Playgrounds.  Uses above)
let package = Package(
    name: "TestLibrary PACKAGE",
    products: [
        .library(
            name: "TestLibrary PACKAGE Library",
            targets: ["TestLibrary PACKAGE"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/kudit/Device", "2.0.7"..<"3.0.0")
    ],
    targets: [
        .target(
            name: "TestLibrary PACKAGE",
            dependencies: [
                .product(name: "Device Library", package: "device"), // apparently needs to be lowercase.  Also note this is "Device Library" not "Device"
            ],
            path: "Sources"
        ),
    ]
)
#endif
