// swift-tools-version: 5.10
// The swift-tools-version declares the minimum version of Swift required to build this package.

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
#if canImport(AppleProductTypes) // swift package dump-package fails because of this
import AppleProductTypes

let package = Package(
    name: "TestLibrary",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .library(
            name: "TestLibrary Library",
            targets: ["TestLibrary"]
        ),
        .iOSApplication(
            name: "TestLibrary",
            targets: ["TestAppModule"],
            teamIdentifier: "3QPV894C33",
            displayVersion: "1.5.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .developerTools
        )
    ],
    dependencies: [
        .package(url: "https://github.com/kudit/Device", "2.0.7"..<"3.0.0")
    ],
    targets: [
        .target(
            name: "TestLibrary",
            dependencies: [
                .product(name: "Device Library", package: "device")
            ],
            path: "Sources"
        ),
        .executableTarget(
            name: "TestAppModule",
            dependencies: [
                "TestLibrary"
            ],
            path: "Development"
        )
    ]
)
#else // for Swift Package compiling for https://swiftpackageindex.com/add-a-package
let package = Package(
    name: "TestLibrary PACKAGE",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .library(
            name: "TestLibrary PACKAGE Library",
            targets: ["TestLibrary PACKAGE"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/kudit/Device", "2.0.7"..<"3.0.0")
    ],
    targets: [
        .target(
            name: "TestLibrary PACKAGE",
            dependencies: [
                .product(name: "Device Library", package: "device")
            ],
            path: "Sources"
        ),
    ]
)
#endif
